# ---------------------------------------------------------------------------
# ArgoCD.
#
# Bootstrap infrastructure, same test as the ALB controller and ingress-nginx:
# without it nothing can deploy, so the cluster is not usable until it exists.
#
# NOTE: ArgoCD needs NO AWS permissions. It only writes to the Kubernetes API.
# Everything AWS-shaped is done by controllers that already hold credentials:
#
#   ArgoCD creates a Service type LoadBalancer  -> ALB controller makes the NLB
#   ArgoCD creates a PVC                        -> EBS CSI driver makes the volume
#   ArgoCD creates a Deployment                 -> kubelet pulls from ECR via the node role
#
# That separation is the point of IRSA: each controller holds only the AWS
# permissions its own job needs, and ArgoCD needs none.
# ---------------------------------------------------------------------------

resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  namespace        = "argocd"
  create_namespace = true

  # Pinned. If this version is unavailable, list what is:
  #   helm repo add argo https://argoproj.github.io/argo-helm
  #   helm search repo argo/argo-cd --versions | head
  version = "7.7.11"

  values = [file("${path.module}/../../helm/argocd-values.yaml")]

  # ArgoCD has several components and a few CRDs to establish; the default
  # 5-minute timeout is tight on a small cluster.
  timeout = 900

  depends_on = [
    aws_eks_node_group.default,

    # Destroy ordering. ArgoCD's own teardown is quick, but anything it
    # deployed (Services with load balancers, PVCs) needs its controllers to
    # still have egress while cleaning up. Same lesson as the ingress-nginx
    # finalizer deadlock.
    aws_route.private_nat,
  ]
}

# The initial admin password, generated by the chart and stored in a Secret.
# Printed as an output so you do not have to go looking for it after every
# cluster rebuild.
data "kubernetes_secret" "argocd_admin" {
  metadata {
    name      = "argocd-initial-admin-secret"
    namespace = "argocd"
  }

  depends_on = [helm_release.argocd]
}

output "argocd_admin_password" {
  description = "Initial admin password. Reach the UI with: kubectl port-forward svc/argocd-server -n argocd 8081:80"
  value       = try(data.kubernetes_secret.argocd_admin.data["password"], "pending")
  sensitive   = true
}
